#ifndef __SILICON_LABS_RTCDRV_CONFIG_H__
#define __SILICON_LABS_RTCDRV_CONFIG_H__

#define EMDRV_RTCDRV_NUM_TIMERS (4)
//#define EMDRV_RTCDRV_WALLCLOCK_CONFIG
#define EMDRV_RTCDRV_SLEEPDRV_INTEGRATION

#endif /* __SILICON_LABS_RTCDRV_CONFIG_H__ */
